### ISSUE TITLE
Monique-web w/ gunicorn initialization issue

### ISSUE THREAD

**Issue by sinaxin** [monique-dashboards/monique-web#1]
Hi,
I followed the README for monique and monique-web, and when I start gunicorn and try to reach the page via port 8100, I get this error from Gunicorn with an Internet Server Error on my browser. 

Thanks!

> [2017-09-15 10:48:28 +0000] [12150] [INFO] Starting gunicorn 19.6.0
[2017-09-15 10:48:28 +0000] [12150] [INFO] Listening at: http://10.10.10.11:8100 (12150)
[2017-09-15 10:48:28 +0000] [12150] [INFO] Using worker: sync
[2017-09-15 10:48:28 +0000] [12155] [INFO] Booting worker with pid: 12155
[2017-09-15 10:48:31 +0000] [12155] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1978, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 332, in push
    self.session = self.app.open_session(self.request)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 912, in open_session
    return self.session_interface.open_session(self, request)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 324, in open_session
    s = self.get_signing_serializer(app)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 321, in get_signing_serializer
    signer_kwargs=signer_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 519, in __init__
    self.is_text_serializer = is_text_serializer(serializer)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 69, in is_text_serializer
    return isinstance(serializer.dumps({}), text_type)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 85, in dumps
    return json.dumps(_tag(value), separators=(',', ':'))
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'iterable_as_array'
[2017-09-15 10:48:32 +0000] [12155] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1978, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 332, in push
    self.session = self.app.open_session(self.request)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 912, in open_session
    return self.session_interface.open_session(self, request)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 324, in open_session
    s = self.get_signing_serializer(app)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 321, in get_signing_serializer
    signer_kwargs=signer_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 519, in __init__
    self.is_text_serializer = is_text_serializer(serializer)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 69, in is_text_serializer
    return isinstance(serializer.dumps({}), text_type)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 85, in dumps
    return json.dumps(_tag(value), separators=(',', ':'))
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'iterable_as_array'

**Comment by aartur** [comment]
That looks like some incompatibility between Flask / simplejson - I don't see monique packages anywhere in the stack. Are other Flask apps working? Maybe try to install it in a virtualenv.

The installation has been tested on Ubuntu 14.04 and Ubuntu 16.04 so generally it should work.

**Comment by sinaxin** [comment]
Ok so I tried with virtualenv, and I still get the same errors. Nothing else uses Flask or simplejson.
I'm on Ubuntu 16.04.

**Comment by aartur** [comment]
Maybe the problem is the compatibility between JSON Decoder/Encoder classes and the given simplejson versions.

Why do you have simplejson installed? It isn't a dependency of Flask or monique. I guess the problem will be fixed when you remove simplejson.

**Comment by sinaxin** [comment]
Removing simplejson fixed the problem!
Thanks for the help!
